import { connectToDatabase } from '@/lib/mongodb'
import { Course } from '@/lib/models'
import ApplyCertificateForm from './ApplyCertificateForm'

export const revalidate = 1800

async function getCourses() {
  await connectToDatabase()
  const docs = await Course.find()
    .sort({ title: 1 })
    .select('_id title isFree hours')
    .lean<{ _id: unknown; title?: string; isFree?: boolean; hours?: number }[]>()

  return docs.map((course) => ({
    _id: String(course._id),
    title: course.title || '',
    isFree: course.isFree || false,
    hours: course.hours || 0,
  }))
}

export default async function ApplyForCertificationPage() {
  const courses = await getCourses()
  const canonicalUrl = "https://nepatronix.org/services/apply-certificate";

  const faqJsonLd = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    "mainEntity": [
      {
        "@type": "Question",
        "name": "Who can apply for a Nepatronix certificate?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Learners who completed a Nepatronix training course can apply for certification using this form."
        }
      },
      {
        "@type": "Question",
        "name": "How long does certificate verification take?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Application review time may vary by intake volume. Approved applications receive a certificate UID for public verification."
        }
      },
      {
        "@type": "Question",
        "name": "Can I verify my certificate online?",
        "acceptedAnswer": {
          "@type": "Answer",
          "text": "Yes. Approved certificates can be verified through the certificate verification URL generated by Nepatronix."
        }
      }
    ]
  };

  const pageJsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    "name": "Apply for Certificate",
    "url": canonicalUrl,
    "description": "Apply for your Nepatronix course completion certificate in IoT, Robotics, and STEM programs.",
    "about": {
      "@type": "EducationalOccupationalCredential",
      "name": "Nepatronix Certificate of Completion"
    }
  };

  return (
    <>
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqJsonLd) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(pageJsonLd) }} />
      <ApplyCertificateForm courses={courses} />
    </>
  );
}
